#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --mem=32GB
#SBATCH --time=20:00:00
#SBATCH --account=ywang234_1137
 
module purge
module load gcc/11.3.0
module load python/3.9.12
module load conda/23.3.1
module load ffmpeg/5.0.1
source ~/.bashrc
conda activate csci677
cd ~/csci677
python3 train.py --model dvig --batch_size 8 --n_train 500 --n_test 100 --epochs 100 > ~/csci677/slurm/output.train_dvig 2> ~/csci677/slurm/err.train_dvig
